### ISSUE TITLE
Is this live on twitter?

### ISSUE THREAD

**Issue by controversial** [yrsegal/shitpost#7]
Is this actively running anywhere I can try it out? If so, that should probably be mentioned in the README.

**Comment by controversial** [comment]
That was quick :+1: Thanks for adding, looks good.

**Comment by yrsegal** [comment]
I'm sick with nothing to do, this wasn't exactly the most complicated of issues to fix x3

**Comment by controversial** [comment]
haha :) Feel better soon.
